name: 'New release'

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to promote to release (default is latest)
        required: false
        default: 'latest'
      name:
        description: Name of this release
        required: true
        default: ''
      tag:
        description: List of commits
        required: true
        default: ''

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency: release

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  CreateRelease:
    runs-on: [ windows-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
      artifacts: ${{ steps.analyzeartifacts.outputs.artifacts }}
      releaseId: ${{ steps.createrelease.outputs.releaseId }}
      commitish: ${{ steps.analyzeartifacts.outputs.commitish }}
      releaseBranch: ${{ steps.createreleasenotes.outputs.releaseBranch }}
    steps:

      - name: Read parameters
        id: readparamters
        run: |
          Write-Host "START!!"
          $listofparameters = ${{ github.event.inputs.tag }}
          $listofparameters = $listofparameters.split(",")
          foreach ($param in $parameters) {
          Write-Host $param
          Write-Host "------"
          }
          Write-Host "END!!"
 
